# Sandbox 1

April 22, 2021

## 1. How to convert list of tuples into np array

In [1]:
import numpy as np

In [20]:
li = []
for i in range(10, 16):
    tup = (i, i**2)
    li.append(tup)
    
li

[(10, 100), (11, 121), (12, 144), (13, 169), (14, 196), (15, 225)]

In [33]:
arr = np.array(li)

arr[:,0]

array([10, 11, 12, 13, 14, 15])

In [22]:
arr[:,1]

array([100, 121, 144, 169, 196, 225])

#### That was easy

## 2. Index slicing on np arrays

In [23]:
arr

array([[ 10, 100],
       [ 11, 121],
       [ 12, 144],
       [ 13, 169],
       [ 14, 196],
       [ 15, 225]])

#### Get the min and max x, y values

In [13]:
x_min = arr[0,0]

x_min

10

In [14]:
y_max = arr[-1,1]

y_max

225

## 3. Make a deep copy of np array

#### First, a shallow copy

In [24]:
arr

array([[ 10, 100],
       [ 11, 121],
       [ 12, 144],
       [ 13, 169],
       [ 14, 196],
       [ 15, 225]])

In [34]:
arr2 = arr

In [35]:
arr[:,1] = arr[:,1]-99

In [36]:
arr

array([[ 10,   1],
       [ 11,  22],
       [ 12,  45],
       [ 13,  70],
       [ 14,  97],
       [ 15, 126]])

In [38]:
arr2

array([[ 10,   1],
       [ 11,  22],
       [ 12,  45],
       [ 13,  70],
       [ 14,  97],
       [ 15, 126]])

#### Deep copy

In [40]:
arr3 = arr.copy()

In [41]:
arr3

array([[ 10,   1],
       [ 11,  22],
       [ 12,  45],
       [ 13,  70],
       [ 14,  97],
       [ 15, 126]])

In [42]:
arr[:,1] = arr[:,1] + 99

arr

array([[ 10, 100],
       [ 11, 121],
       [ 12, 144],
       [ 13, 169],
       [ 14, 196],
       [ 15, 225]])

In [43]:
arr3

array([[ 10,   1],
       [ 11,  22],
       [ 12,  45],
       [ 13,  70],
       [ 14,  97],
       [ 15, 126]])

## 3. Inspect dataset

In [50]:
import pandas as pd

In [46]:
arr = np.load('../data/arr50.npy')

In [52]:
df = pd.DataFrame(arr, columns = ['fare', 'age', 'survived'])

In [54]:
df.describe()

fare        age   survived
count   50.000000  50.000000  50.000000
mean    30.334498  30.190000   0.340000
std     31.164935  18.385578   0.478518
min      0.000000   2.000000   0.000000
25%      8.801050  17.000000   0.000000
50%     20.400000  28.000000   0.000000
75%     31.521850  42.000000   1.000000
max    120.000000  71.000000   1.000000

In [57]:
df[df.fare > 0].min()

fare        6.975
age         2.000
survived    0.000
dtype: float64

#### Note: 6.975 was 817 GBP, or 1400 CAD