# KNN algo 

April 23, 2021

In [2]:
import numpy as np

In [82]:
arr = np.load('../data/arr30.npy')

In [83]:
arr[:5]

array([[ 7.2292, 17.    ,  0.    ],
       [ 9.    , 47.    ,  0.    ],
       [ 7.925 , 44.    ,  1.    ],
       [ 7.75  , 29.    ,  1.    ],
       [40.125 , 36.    ,  0.    ]])

## 1. Euclidian distance

In [65]:
a = (arr[0,:2])
b = (arr[1,:2])

In [66]:
print(a)
print(b)

[ 7.2292 17.    ]
[ 9. 47.]


#### Do it manually

In [14]:
import math as m

In [67]:
m.sqrt( (b[0] - a[0])**2 + (b[1] - a[1])**2 )

30.052216767486556

#### Do it manually in numpy

In [70]:
np.sqrt(np.sum(np.square(a-b)))

30.052216767486556

## 2. Get Euclid on norm_arr

In [125]:
arr_orig = np.load('../data/arr30.npy')

In [126]:
zeros = np.zeros( (30, 2) )
arr = np.concatenate( (arr_orig, zeros), axis=1 )
arr[:5]

array([[ 7.2292, 17.    ,  0.    ,  0.    ,  0.    ],
       [ 9.    , 47.    ,  0.    ,  0.    ,  0.    ],
       [ 7.925 , 44.    ,  1.    ,  0.    ,  0.    ],
       [ 7.75  , 29.    ,  1.    ,  0.    ,  0.    ],
       [40.125 , 36.    ,  0.    ,  0.    ,  0.    ]])

#### Note: -2 = euclid, -1 = bool for whether top K

In [86]:
fare = 11
age = 25

mid_coord = [fare, age]
mid_coord

[11, 25]

In [40]:
arr[:5,:2]

array([[ 7.2292, 17.    ],
       [ 9.    , 47.    ],
       [ 7.925 , 44.    ],
       [ 7.75  , 29.    ],
       [40.125 , 36.    ]])

In [127]:
for i, coord in enumerate(arr[:,:2]):
    arr[i,3] = np.sqrt(np.sum(np.square(coord-mid_coord)))

In [128]:
arr[:5]

array([[ 7.2292    , 17.        ,  0.        ,  8.8441468 ,  0.        ],
       [ 9.        , 47.        ,  0.        , 22.09072203,  0.        ],
       [ 7.925     , 44.        ,  1.        , 19.24722383,  0.        ],
       [ 7.75      , 29.        ,  1.        ,  5.15388203,  0.        ],
       [40.125     , 36.        ,  0.        , 31.13303109,  0.        ]])

## 3. Get the K min distances

In [90]:
k = 7

#### argpartition returns index values of least

In [129]:
x = np.argpartition(arr[:,3], 7)
x

array([ 5, 22, 11,  3, 13, 27, 20,  0, 26, 16, 15, 12,  8, 14,  1, 10,  9,
       17, 18, 19,  7, 21,  6, 23, 24, 25,  4,  2, 28, 29], dtype=int64)

In [133]:
arr[x[:k],4] = 1

In [134]:
arr[:,2:]

array([[  0.        ,   8.8441468 ,   0.        ],
       [  0.        ,  22.09072203,   0.        ],
       [  1.        ,  19.24722383,   0.        ],
       [  1.        ,   5.15388203,   1.        ],
       [  0.        ,  31.13303109,   0.        ],
       [  0.        ,   3.35410197,   1.        ],
       [  1.        ,  22.53907718,   0.        ],
       [  1.        , 501.44986467,   0.        ],
       [  0.        ,  16.55375539,   0.        ],
       [  0.        ,  34.68144316,   0.        ],
       [  1.        ,  25.30978373,   0.        ],
       [  1.        ,   5.22015325,   1.        ],
       [  0.        ,  11.18033989,   0.        ],
       [  0.        ,   5.85768726,   1.        ],
       [  0.        ,  17.49285568,   0.        ],
       [  1.        ,   9.21954446,   0.        ],
       [  0.        ,   9.56036741,   0.        ],
       [  1.        ,  18.26766696,   0.        ],
       [  0.        ,  71.23400012,   0.        ],
       [  1.        ,  82.65137

In [147]:
arr = np.zeros( (10, 2) )

In [162]:
np.random.random_integers(2, 10, 10)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(2, 10 + 1) instead
  """Entry point for launching an IPython kernel.


array([ 8, 10,  6,  5,  7,  2,  3,  2, 10,  6])

In [163]:
arr[:,0] = np.random.random_integers(2, 10, 10)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(2, 10 + 1) instead
  """Entry point for launching an IPython kernel.


In [164]:
x = np.argpartition(arr[:,0], 3)

In [165]:
x

array([3, 8, 4, 5, 1, 6, 0, 7, 2, 9], dtype=int64)

In [166]:
arr[:,0]

array([ 9.,  7., 10.,  3.,  2.,  7.,  8., 10.,  3.,  9.])

In [168]:
arr[x[:3]]

array([[3., 0.],
       [3., 0.],
       [2., 0.]])

In [169]:
arr[x[:3]] = 1

arr

array([[ 9.,  0.],
       [ 7.,  0.],
       [10.,  0.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 7.,  0.],
       [ 8.,  0.],
       [10.,  0.],
       [ 1.,  1.],
       [ 9.,  0.]])

## 4.0 Reset an entire col to zeros

### 4.1 Reset one col

In [198]:
arr = np.zeros( (6, 2) )
arr[:,0] = np.random.randint(1, 10, 6)
arr[:,1] = np.random.randint(1, 10, 6)

arr

array([[2., 4.],
       [2., 5.],
       [2., 8.],
       [2., 6.],
       [2., 8.],
       [3., 1.]])

In [199]:
arr[:,0] = 0

arr

array([[0., 4.],
       [0., 5.],
       [0., 8.],
       [0., 6.],
       [0., 8.],
       [0., 1.]])

### 4.2 Reset two cols

In [205]:
arr = np.zeros( (6, 3) )
arr[:,0] = np.random.randint(1, 10, 6)
arr[:,1] = np.random.randint(1, 10, 6)
arr[:,2] = np.random.randint(1, 10, 6)

arr

array([[7., 7., 1.],
       [4., 4., 4.],
       [9., 2., 5.],
       [9., 5., 5.],
       [7., 5., 8.],
       [4., 9., 7.]])

In [206]:
arr[:,1:] = 0
arr

array([[7., 0., 0.],
       [4., 0., 0.],
       [9., 0., 0.],
       [9., 0., 0.],
       [7., 0., 0.],
       [4., 0., 0.]])

## 5. Set radius equal to the furthest nn
- I need the coordinates 
    - Because you cannot convert arr distances to pixel distances
    - Only coordinates

### 5.1 Prepare a realistic array

In [246]:
arr = np.load('../data/arr30.npy')

In [247]:
zeros = np.zeros( (30, 1) )
arr = np.concatenate( (arr_orig, zeros), axis=1 )
arr[:5]

array([[ 7.2292, 17.    ,  0.    ,  0.    ],
       [ 9.    , 47.    ,  0.    ,  0.    ],
       [ 7.925 , 44.    ,  1.    ,  0.    ],
       [ 7.75  , 29.    ,  1.    ,  0.    ],
       [40.125 , 36.    ,  0.    ,  0.    ]])

### 5.2 Do euclid on it

In [248]:
for i, coord in enumerate(arr[:,:2]):
    arr[i,3] = np.sqrt(np.sum(np.square(coord-mid_coord)))

In [249]:
arr[:5]

array([[ 7.2292    , 17.        ,  0.        ,  8.8441468 ],
       [ 9.        , 47.        ,  0.        , 22.09072203],
       [ 7.925     , 44.        ,  1.        , 19.24722383],
       [ 7.75      , 29.        ,  1.        ,  5.15388203],
       [40.125     , 36.        ,  0.        , 31.13303109]])

### 5.3 Partition into K nn

In [250]:
K = 7

x = np.argpartition(arr[:,3], K)
x

array([ 5, 22, 11,  3, 13, 27, 20,  0, 26, 16, 15, 12,  8, 14,  1, 10,  9,
       17, 18, 19,  7, 21,  6, 23, 24, 25,  4,  2, 28, 29], dtype=int64)

In [251]:
arr[x[:K]]

array([[ 9.5       , 28.        ,  0.        ,  3.35410197],
       [ 8.05      , 20.        ,  0.        ,  5.80538543],
       [ 9.5       , 30.        ,  1.        ,  5.22015325],
       [ 7.75      , 29.        ,  1.        ,  5.15388203],
       [ 7.25      , 20.5       ,  0.        ,  5.85768726],
       [ 7.8542    , 31.        ,  0.        ,  6.77466292],
       [ 7.775     , 31.        ,  0.        ,  6.81180042]])

In [252]:
arr[x[K:K+5]]

array([[ 7.2292    , 17.        ,  0.        ,  8.8441468 ],
       [13.        , 34.        ,  1.        ,  9.21954446],
       [ 7.775     , 16.        ,  0.        ,  9.56036741],
       [13.        , 34.        ,  1.        ,  9.21954446],
       [13.        , 36.        ,  0.        , 11.18033989]])

### 5.4 Get the max distance in the partition

In [253]:
part = arr[x[:K]]
mx = part[:,3].max()
mx

6.811800422795724

### 5.5 Get index of max distance in partition

#### Get an index from a numpy arr

In [222]:
arr2 = np.random.randint(1,200,10)
arr2

array([ 21, 168, 171, 130,  91,  76,  90,  72, 171,  37])

In [230]:
np.where(arr2 == 37)

(array([9], dtype=int64),)

In [231]:
x = np.where(arr2 == 37)

arr2[x]

array([37])

#### Let's do on the full array

In [254]:
mx

6.811800422795724

In [255]:
np.where(arr == mx)

(array([20], dtype=int64), array([3], dtype=int64))

In [256]:
arr[19:22]

array([[93.5       , 30.        ,  1.        , 82.65137627],
       [ 7.775     , 31.        ,  0.        ,  6.81180042],
       [71.        , 36.        ,  1.        , 61.        ]])

#### It's weird -- it doesn't return the index, you have to slice for that

In [259]:
np.where(arr == mx)[0][0]

20

In [260]:
x = np.where(arr == mx)[0][0]

In [261]:
arr[x,:2]

array([ 7.775, 31.   ])

## 6. Get sum of survived col

In [263]:
arr[:3]

array([[ 7.2292    , 17.        ,  0.        ,  8.8441468 ],
       [ 9.        , 47.        ,  0.        , 22.09072203],
       [ 7.925     , 44.        ,  1.        , 19.24722383]])

In [265]:
arr[:,2].sum()

15.0