# Titanic dataset -- Can I do KNN with numpy not pandas?

April 19, 2021

- Using Pandas outside Jupyter is weird

In [3]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

## 1. Import numpy array

In [8]:
df = pd.read_csv('data/titanic_basic.csv', index_col = 0)
df.head()

fare   age  survived
0   7.2500  22.0         0
1  71.2833  38.0         1
2   7.9250  26.0         1
3  53.1000  35.0         1
4   8.0500  35.0         0

In [10]:
arr = np.load('data/titanic.npy')

In [11]:
arr

array([[ 7.25  , 22.    ,  0.    ],
       [71.2833, 38.    ,  1.    ],
       [ 7.925 , 26.    ,  1.    ],
       ...,
       [30.    , 19.    ,  1.    ],
       [30.    , 26.    ,  1.    ],
       [ 7.75  , 32.    ,  0.    ]])

#### Proof that my arr equals the df I used in the previous notebook

In [15]:
df2 = pd.DataFrame(arr, columns = df.columns)

df2.head()

fare   age  survived
0   7.2500  22.0       0.0
1  71.2833  38.0       1.0
2   7.9250  26.0       1.0
3  53.1000  35.0       1.0
4   8.0500  35.0       0.0

### 1.1 Standardize the data

In [16]:
len(arr)

714

#### ^^ So, confirming this has dropped na values. 

In [17]:
scaler = StandardScaler()

#### Select first two columns

In [26]:
arr2 = arr[:, [0,1] ]

arr2[:3]

array([[ 7.25  , 22.    ],
       [71.2833, 38.    ],
       [ 7.925 , 26.    ]])

In [27]:
scaler.fit(arr2)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [30]:
scaled_features = scaler.transform(arr2)

scaled_features[:3]

array([[-0.51897787, -0.53037664],
       [ 0.69189675,  0.57183099],
       [-0.50621356, -0.25482473]])

## 2. Train test split

In [33]:
X = arr2
y = arr[:,2]
y[:5]

array([0., 1., 1., 1., 0.])

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## 3. KNN

In [35]:
knn = KNeighborsClassifier(n_neighbors=23)

knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=23, p=2,
                     weights='uniform')

In [36]:
pred = knn.predict(X_test)

## 4. Evaluate KNN

In [37]:
from sklearn.metrics import classification_report, confusion_matrix

In [39]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

         0.0       0.69      0.85      0.76       137
         1.0       0.70      0.47      0.57        99

    accuracy                           0.69       236
   macro avg       0.70      0.66      0.67       236
weighted avg       0.70      0.69      0.68       236



## Woot!! 

- I just proved I can do KNN with sklearn, without touching Pandas!!

### I'll use this as the model against which to check performance

## 5. Note: I think I want to actually make predictions... not get a precision and recall score.

- It can be done with just knn.predict([fare, age])
    - But those values have to be standardized
    - So, <b>a challenge in this may be to figure out how to standardize on the fly... </b>
        - I.e., The pygame 'game' could let you drag a hypothetical passenger (fare/age) to a spot to see if they survive.


### I may need to dig into the math behind sklearn's autoscaler.